// Auth Types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';

// Home Types
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const SET_REMINDER_SUCCESS = 'SET_REMINDER_SUCCESS';
export const GET_REMINDERS_SUCCESS = 'GET_REMINDERS_SUCCESS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
